"""Disbursement model for tracking loan fund releases.

Designed for manual disbursement now, with fields ready for payment
system integration (bank transfer, mobile money, etc.)."""

import enum
from datetime import datetime
from sqlalchemy import (
    String, Numeric, Integer, Enum as SAEnum, DateTime, ForeignKey, Text, JSON, func
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class DisbursementMethod(str, enum.Enum):
    """How funds are released. Manual for now; extensible to integrations."""
    MANUAL = "manual"              # Cash / cheque / internal transfer
    BANK_TRANSFER = "bank_transfer"
    MOBILE_MONEY = "mobile_money"
    WALLET = "wallet"
    CHEQUE = "cheque"


class DisbursementStatus(str, enum.Enum):
    """Lifecycle of a disbursement.

    PENDING   – created, awaiting confirmation.
    PROCESSING – sent to external payment provider (future).
    COMPLETED – funds confirmed released.
    FAILED    – external provider reported failure (future).
    REVERSED  – disbursement clawed back / cancelled.
    """
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"
    REVERSED = "reversed"


class Disbursement(Base):
    __tablename__ = "disbursements"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    loan_application_id: Mapped[int] = mapped_column(
        ForeignKey("loan_applications.id"), nullable=False, index=True
    )

    # Amount & method
    amount: Mapped[float] = mapped_column(Numeric(12, 2), nullable=False)
    method: Mapped[DisbursementMethod] = mapped_column(
        SAEnum(DisbursementMethod, values_callable=lambda e: [m.value for m in e]),
        nullable=False, default=DisbursementMethod.MANUAL
    )
    status: Mapped[DisbursementStatus] = mapped_column(
        SAEnum(DisbursementStatus, values_callable=lambda e: [m.value for m in e]),
        nullable=False, default=DisbursementStatus.COMPLETED
    )

    # Internal reference (generated by Zotta)
    reference_number: Mapped[str | None] = mapped_column(
        String(50), unique=True, nullable=True, index=True
    )

    # External payment provider fields (for future integrations)
    provider: Mapped[str | None] = mapped_column(String(50), nullable=True)
    provider_reference: Mapped[str | None] = mapped_column(String(100), nullable=True)
    provider_response: Mapped[dict | None] = mapped_column(JSON, nullable=True)

    # Bank / recipient details (for bank transfer integration)
    recipient_account_name: Mapped[str | None] = mapped_column(String(200), nullable=True)
    recipient_account_number: Mapped[str | None] = mapped_column(String(50), nullable=True)
    recipient_bank: Mapped[str | None] = mapped_column(String(100), nullable=True)
    recipient_bank_branch: Mapped[str | None] = mapped_column(String(100), nullable=True)

    # Operator
    disbursed_by: Mapped[int] = mapped_column(
        ForeignKey("users.id"), nullable=False
    )
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Timestamps
    disbursed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    # Relationships
    loan_application = relationship("LoanApplication", backref="disbursements")
    operator = relationship("User", foreign_keys=[disbursed_by])
